server:
  port: ${port:12085}
spring:
  profiles:
    active: "dev-ogya"
  main:
    banner-mode: "off"
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
---
spring:
  profiles: dev-local
  dataSource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  json:
    file:
      user: D:\\\var\\bca\\file\\user.json
---
spring:
  profiles: dev-ogya
  dataSource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  json:
    file:
      user: /var/bca/file/user.json
